# Generated by Django 3.2.9 on 2022-04-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220429_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetailslist',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
